Dummy Blender-save support Documentation
git-svn-id: svn://svn.code.sf.net/p/fracplanet/code/trunk@109 b61c5637-9d11-496f-99c9-1cb6e07b56bf

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -23,7 +23,7 @@ gcc --version
 
 echo
 echo "Building built-in user manual..."
-if ! xsltproc -html htm_to_qml.xsl fracplanet.htm | sed 's/"/\\"/g' | sed 's/^/"/g' | sed 's/$/\\n"/g'> usage_text.h ; then echo "Couldn't build usage_text.h" ; fi
+if ! xsltproc -stringparam version `./VERSION` -html htm_to_qml.xsl fracplanet.htm | sed 's/"/\\"/g' | sed 's/^/"/g' | sed 's/$/\\n"/g'> usage_text.h ; then echo "Couldn't build usage_text.h" ; fi
 if ! test -s usage_text.h ; then echo "\"Full built-in user documentation not available due to problem during build configuration.  Maybe the builder didn't have xsltproc or sed installed ?\"" > usage_text.h ; echo "Something went wrong, used built-in user documentation fallback plan"; fi
 echo "...built built-in user documentation"
 
